config/routes.rb
Rails.application.routes.draw do
  resources :images do
    collection do
      post :confirm
    end
  end

  root "sessions#new"

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user
  mount_uploader :picture, PictureUploader
  validates :name, presence: true, length: { maximum: 63206 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :images, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :username, presence: true,
                      uniqueness: { case_sensitive: false },
                      length: { minimum: 3, maximum: 25 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { maximum: 105 },
                    format: { with: VALID_EMAIL_REGEX }

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end

  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def page_title
    "Facebook"
  end

  def index
    @images = Image.all
  end

  def show
  end

  def new
    @image = Image.new
  end

  def edit
  end

  def create
    @image = Image.new(image_params)
    @image.user = current_user
    if params[:back]
      render :new
    else
      if @image.save
        flash[:notice] = "image Created"
        redirect_to @image
      else
        render 'new'
      end
    end
  end

  def update
    if @image.update(image_params)
      flash[:notice] = "Edited Successfully"
      redirect_to @image
    else
      render 'edit'
    end
  end

  def destroy
    if @image.destroy
      flash[:notice] = "Deleted Successfully"
      redirect_to images_path
    end
  end

  def confirm
    @image = Image.new(image_params)
    @image.user = current_user
    render 'new' if @image.invalid?
  end

  private

  def set_image
    @image = Image.find(params[:id])
  end

  def image_params
    params.require(:image).permit(:name, :picture, :picture_cache, :user_id)
  end

  def require_same_user
    if current_user != @image.user
      flash[:alert] = "You can only edit or delete your own posts"
      redirect_to @image
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def page_title
    "Facebook - login or signup"
  end

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in successfully"
      redirect_to user
    else
      flash[:danger] = "Invalid email or password"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:new, :create]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def page_title
    "Facebook"
  end

  def index
    @users = User.all
  end

  def show
    @images = @user.images
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome #{@user.username}, you have successfully signed up"
      redirect_to @user
    else
      render 'new'
    end
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your account information was successfully updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil
    flash[:notice] = "Account and all associated posts successfully deleted"
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user
      flash[:alert] = "You can only edit your own account"
      redirect_to @user
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user, options = { size: 80})
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mt-4 mx-auto d-block")
  end

end

app/helpers/images_helper.rb
module ImagesHelper

  def choose_new_or_edit_image
    if action_name == 'new' || action_name == 'create'
      confirm_images_path
    elsif action_name == 'edit'
      image_path
    end
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/images/_form.html.erb
<div class="container mt-5">
  <%= form_with(model: @image, local: true, url: choose_new_or_edit_image) do |f| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-3">
        <%= render 'shared/errors', obj: @image %>
        <div class="card text-center">
          <div class="card-header bg-grey text-center font-weight-bold my-font-size">
            <p><%= post %></p>
          </div>

          <div class="card-body" style="height: 27rem;">

            <p class="card-text text-center">
              <%= f.text_area :name, rows: "14", autofocus: true,
              class: "form-control", placeholder: "What's on your mind? #{current_user.username}" %>
            </p>

            <p class="card-text text-left">
              <%= f.file_field :picture %>
              <%= f.hidden_field :picture_cache %>
            </p>

          </div>

          <div class="card-footer">
            <p>
              <%= f.submit "#{name}", class: "btn my-color text-white btn-lg btn-block" %>
            </p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/images/_image.html.erb
<div class="container">
  <% @images.each do |image| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-3">
        <div class="card text-center shadow-sm p-3">
          <div class="card-header bg-white text-left text-primary font-weight-bold">
            <h5><%= link_to image.user.username, user_path(image.user) %></h5>
          </div>
          <div class="card-body">
            <p class="card-text text-left"><%= image.name %></p>
            <p class="card-text text-center"><%= image_tag(image.picture.url, size: "570x300") if image.picture? %></p>
            <%= link_to 'View', image_path(image), class: "btn btn-outline-info px-4" %>
            <% if logged_in? && image.user == current_user %>
              <%= link_to 'Edit', edit_image_path(image), class: "btn btn-outline-primary px-4" %>
              <%= link_to 'Delete', image_path(image), method: :delete, data: { confirm: "Are you sure?" },
              class: "btn btn-outline-danger px-4" %>
            <% end %>
          </div>
          <div class="card-footer text-muted bg-white">
            <small>Created <%= time_ago_in_words(image.created_at) %> ago,
            edited <%= time_ago_in_words(image.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/images/confirm.html.erb
<div class="container">
  <%= form_with(model: @image, url: images_path, local: true) do |f| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-3">
        <%= render 'shared/errors', obj: @image %>
        <div class="card text-center">
          <div class="card-header bg-grey text-center font-weight-bold my-font-size">
            <p>Send with the following contents</p>
          </div>
          <div class="card-body" style="height: 25rem;">
            <%= f.hidden_field :name %>
            <p><%= @image.name %></p>
            <%= f.hidden_field :picture_cache %>
            <p class="card-text"><%= image_tag(@image.picture.url, size: "570x300") if @image.picture? %></p>
          </div>
          <div class="card-footer">
            <p>
              <%= f.submit "Register", class: "btn btn-outline-primary px-4" %>
              <%= f.submit "Back", name:'back', class: "btn btn-outline-primary px-4" %>
            </p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/images/edit.html.erb
<%= render 'shared/nav' %>
<%= render 'form', post: "Edit Post", name: "Save" %>

app/views/images/index.html.erb
<%= render 'shared/nav' %>
<%= render 'shared/messages' %>
<h1 class="text-center mt-3 mb-2">Home Page</h1>
<%= render 'image' %>

app/views/images/new.html.erb
<%= render 'shared/nav' %>
<%= render 'form', post: "New Post", name: "Post" %>

app/views/images/show.html.erb
<%= render 'shared/nav' %>
<%= render 'shared/messages' %>

<div class="container">
    <div class="row justify-content-md-center">
      <div class="col-8 mt-3">
        <h1 class="text-center mt-0 mb-4">Post Details</h1>
        <div class="card text-center">
          <div class="card-header bg-white text-center text-primary font-weight-bold">
            <h4><%= link_to @image.user.username, user_path(@image.user) %></h4>
            <%= link_to gravatar_for(@image.user), user_path(@image.user) %>
          </div>
          <div class="card-body">
            <div class="card-text text-center"><%= @image.name %></div>
            <div class="m-4"><%= image_tag(@image.picture.url, size: "570x300") if @image.picture? %></div>
            <% if logged_in? && @image.user == current_user %>
              <%= link_to 'Edit', edit_image_path(@image), class: "btn btn-outline-primary px-4" %>
              <%= link_to 'Delete', image_path(@image), method: :delete, data: { confirm: "Are you sure?" },
              class: "btn btn-outline-danger px-4" %>
            <% end %>
          </div>
          <div class="card-footer text-muted bg-white">
            <small>Created <%= time_ago_in_words(@image.created_at) %> ago,
            edited <%= time_ago_in_words(@image.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-sm sticky-top">
  <!-- Brand -->
  <a class="navbar-brand text-white" href="#">Facebook</a>

  <!-- Links -->
  <div class="nav-center">

    <ul class="navbar-nav">

      <li class="nav-item">
        <a class="nav-link text-white" href="#">Profile</a>
      </li>
      <li class="nav-item">
        <%= link_to 'Home', posts_path, class: "nav-link text-white" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Create Post', new_post_path, class: "nav-link text-white" %>
      </li>

    </ul>

  </div>

  <div class="nav-right">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link text-white" href="#">Log Out</a>
      </li>
    </ul>
  </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=controller.page_title%></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <footer class="shadow">
      <p>Copyright &copy; SOE ZAYAR</p>
    </footer>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved!</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_messages.html.erb
<div class="container mb-2">
  <% flash.each do |name, msg| %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
    <%= msg %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar sticky-top shadow-sm navbar-expand-md navbar-light bg-light">
  <%= link_to 'Facebook', images_path, class: "navbar-brand my-text-brand col-md-4" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse col-md-8" id="navbarNav">
      <div class="navbar-nav col-md-8">
        <div class="nav-item col-md-2">
          <%= link_to 'Users', users_path, class: "nav-link my-text" %>
        </div>
        <div class="nav-item col-md-2">
          <%= link_to 'Home', images_path, class: "nav-link my-text" %>
        </div>
        <div class="nav-item col-md-3">
          <%= link_to 'Create Post', new_image_path, class: "nav-link my-text" %>
        </div>
      </div>
      <div class="navbar-nav col-md-4">
        <div class="nav-item col-md-5">
          <%= link_to "#{current_user.username}", user_path(current_user),
          class: "nav-link my-text" %>
        </div>
        <div class="nav-item col-md-5">
          <%= link_to 'Log Out', logout_path, class: "nav-link my-text", method: :delete %>
        </div>
      </div>
  </div>
</nav>

app/views/users/_form.html.erb
<div class="container mb-0">
  <%= form_with(model: @user, local: true) do |f| %>
    <div class="row justify-content-md-center">
      <div class="col-6 mt-5">
        <%= render 'shared/errors', obj: @user %>
        <div class="card shadow text-center">
          <div class="card-header bg-grey text-left">
            <h1 class=" font-weight-bold"><%= "#{type}" %></h1>
            <p class="text-muted"><%= "#{text}" %></p>
          </div>
          <div class="card-body", style="height: 240px;">
            <p class="card-text text-center mt-3"><%= f.text_field :username, autofocus: true,
            class: "form-control shadow-sm", placeholder: "Username" %></p>
            <p class="card-text text-center mt-4"><%= f.email_field :email,
            class: "form-control shadow-sm", placeholder: "Email address" %></p>
            <p class="card-text text-center"><%= f.password_field :password,
            class: "form-control shadow-sm mt-4", placeholder: "New password" %></p>
          </div>
          <div class="card-footer">
            <p>
              <%= f.submit "#{name}",
              class: "btn btn-success text-white btn-lg btn-block" %>
            </p>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= render 'shared/nav' %>
<%= render 'form', type: 'Edit your profile', text: '',
name: 'Update Account' %>

app/views/users/index.html.erb
<%= render 'shared/nav' %>
<%= render 'shared/messages' %>

<h1 class="text-center mt-3 mb-2">Facebook Users</h1>
<div class="container">
  <% @users.each do |user| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-3">
        <div class="card text-center shadow-sm p-3">
          <div class="card-header bg-white text-center text-primary font-weight-bold">
            <%= link_to user.username, user %>
          </div>
          <div class="card-body">
            <p class="card-text"><%= gravatar_for(user, size: 150) %></p>
            <p class="card-text text-center"><%= pluralize(user.images.count, "post") %></p>
            <%= link_to 'View Profile', user, class: "btn btn-outline-info px-4" %>
            <% if logged_in? && user == current_user %>
              <%= link_to 'Edit Profile', edit_user_path(user),
              class: "btn btn-outline-primary px-4" %>
            <% end %>
          </div>
          <div class="card-footer text-muted bg-white">
            <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<%= render 'form', type: 'Sign Up', text: 'It\'s quick and easy.',
name: 'Sign Up' %>

<div class="container text-center mt-4">
  <%= link_to 'Back to Log In', login_path %>
</div>

app/views/users/show.html.erb
<%= render 'shared/nav' %>
<%= render 'shared/messages' %>

<h1 class="text-center mt-4"><%= @user.username %>'s profile</h1>
<%= gravatar_for @user, size: 200 %>
<div class="text-center mt-4">
  <% if logged_in? && @user == current_user %>
    <%= link_to 'Edit Profile', edit_user_path(@user),
    class: "btn btn-outline-primary px-4" %>
    <%= link_to 'Delete Account', user_path(@user), method: :delete, data: { confirm: "Are you sure?" },
    class: "btn btn-outline-danger px-4" %>
  <% end %>
</div>
<h3 class="text-center mt-4">Posts</h3>
<%= render 'images/image' %>